djtest/urls.py
from django.conf.urls import include, url
from polls import views
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^myapp/', include('myapp.urls', namespace="myapp")),
    url(r'^index/$', views.index),
    url(r'^captcha', include('captcha.urls')),
]

myapp/urls.py
#!/usr/bin/env python3
# encoding:utf-8
'''
@author: lierl
@file: urls.py
@time: 2018/4/1 12:32
'''
__author__ = 'lierl'

from . import views
from django.conf.urls import url, include

app_name='myapp'

urlpatterns = [
    url(r'^index/', views.index, name="index"),
    url(r'^login/', views.login, name="login"),
    url(r'^register/', views.register, name="register"),
    url(r'^logout/', views.logout, name="logout"),
    url(r'^confirm/', views.confirm, name="confirm"),
    url(r'^test/', views.testQuery, name="test"),
]

myapp/models.py
from django.db import models
from datetime import timezone, timedelta, datetime
#python manage.py makemigrations myapp
#python manage.py migrate myapp
# Create your models here.
class User(models.Model):
    gender = (
        ('male', '男'),
        ('female', '女')
    )
    name = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    #性别使用了一个choice，只能选择男或者女，默认为男；
    sex = models.CharField(max_length=10,choices=gender, default='男')
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    #用来区别用户是否进行了邮箱验证
    has_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "t_user"
        ordering = ["-create_time"]
        verbose_name = "用户"
        verbose_name_plural="用户"

#保存了用户和注册码之间的关系，一对一的形式
class ConfirmString(models.Model):
    code = models.CharField(max_length=256)#哈希后的注册码
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['create_time']
        verbose_name="确认码"
        verbose_name_plural="确认码"

    def __str__(self):
        return self.user.name+": "+ self.code

myapp/forms.py
#!/usr/bin/env python3
# encoding:utf-8
'''
@author: lierl
@file: forms.py
@time: 2018/4/1 16:40
'''
__author__ = 'lierl'

from django import forms
from captcha.fields import CaptchaField

'''
说明：
1、要先导入forms模块
2、所有的表单类都要继承forms.Form类
3、每个表单字段都有自己的字段类型比如CharField，它们分别对应一种HTML语言中<form>内的一个input元素。这一点和Django模型系统的设计非常相似。
4、label参数用于设置<label>标签
5、max_length限制字段输入的最大长度。它同时起到两个作用，一是在浏览器页面限制用户输入不可超过字符数，二是在后端服务器验证用户输入的长度也不可超过。
6、widget=forms.PasswordInput用于指定该字段在form表单里表现为<input type='password' />，也就是密码输入框。
'''
class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label="验证码")

'''
说明：
1、gender和User模型中的一样，其实可以拉出来作为常量共用，为了直观，特意重写一遍；
2、password1和password2，用于输入两遍密码，并进行比较，防止误输密码；
3、email是一个邮箱输入框；
4、sex是一个select下拉框；
'''
class RegisterForm(forms.Form):
    gender = (
        ('male', '男'),
        ('female', '女')
    )
    username = forms.CharField(label="用户名", max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label="性别", choices=gender, widget=forms.Select(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label="验证码")




    pass

myapp/views.py
from django.shortcuts import render, redirect
# Create your views here.
from myapp.models import User, ConfirmString
from myapp.utils import get_md5, send_email
from myapp import forms
from myapp.apps import MyappConfig
import datetime
from djtest import settings
from django.http import HttpResponse

def index(request):
    # type(request) <class 'django.core.handlers.wsgi.WSGIRequest'>
    return render(request=request, template_name="index.html")

'''
说明：
1、每个视图函数都至少接收一个参数，并且是第一位置参数，该参数封装了当前请求的所有数据；
2、通常将第一参数命名为request，当然也可以是别的；
3、request.method中封装了数据请求的方法，如果是“POST”（全大写），将执行if语句的内容，如果不是，直接返回最后的render()结果；
4、request.POST封装了所有POST请求中的数据，这是一个字典类型，可以通过get方法获取具体的值。
5、类似get('username')中的键‘username’是HTML模板中表单的input元素里‘name’属性定义的值。所以在编写form表单的时候一定不能忘记添加name属性。
6、利用print函数在开发环境中验证数据；
7、利用redirect方法，将页面重定向到index页。
'''
#不适用form接收参数
def login1(request):
    if request.method == 'POST':
        username = request.POST.get('username',None)
        password = request.POST.get('password', None)
        print(username, password)
        #判断用户密码不能为空
        if username and password:
            '''
            通过get('username', None)的调用方法，确保当数据请求中没有username键时不会抛出异常，而是返回一个我们指定的默认值None；
            通过if username and password:确保用户名和密码都不为空；
            通过strip()方法，将用户名前后无效的空格剪除；
            更多的数据验证需要根据实际情况增加，原则是以最低的信任度对待发送过来的数据。
            '''
            username = username.strip()
            try:
                user = User.objects.get(name=username)
            except:
                return render(request=request, template_name="login.html", context={"error": "用户名或密码不正确"})
            if user.password == password:
                return redirect("/%s/index/" % MyappConfig.name)#重定向到首页
    return render(request=request, template_name="login.html")

'''
说明：
1、对于非POST方法发送数据时，比如GET方法请求页面，返回空的表单，让用户可以填入数据；
2、对于POST方法，接收表单数据，并验证；
3、使用表单类自带的is_valid()方法一步完成数据验证工作；
4、验证成功后可以从表单对象的cleaned_data数据字典中获取表单的具体值；
5、如果验证不通过，则返回一个包含先前数据的表单给前端页面，方便用户修改。也就是说，它会帮你保留先前填写的数据内容，而不是返回一个空表！
    另外，这里使用了一个小技巧，Python内置了一个locals()函数，它返回当前所有的本地变量字典，我们可以偷懒的将这作为render函数的数据字典参数值，就不用费劲去构造一个形如{'message':message, 'login_form':login_form}的字典了。这样做的好处当然是大大方便了我们，但是同时也可能往模板传入了一些多余的变量数据，造成数据冗余降低效率。
'''
def login(request):
    if request.session.get('is_login', None):
        #如果已经登录，则直接跳转到首页
        return redirect("/%s/index/" % MyappConfig.name)

    if request.method == 'POST':
        login_form = forms.UserForm(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = User.objects.get(name=username)
                if user.password == get_md5(password):
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect("/%s/index/" % MyappConfig.name)#重定向到首页
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
    login_form = forms.UserForm()
    return render(request=request, template_name="login.html", context=locals())

#创建确认码
def make_confirm_string(user):
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    code = get_md5(user.name, now)

    ConfirmString.objects.create(code=code, user=user)
    return code


def register(request):
    #首先判断当前用户是否是登录状态，如果是登录状态跳转到首页
    if request.session.get('is_login', None):
        return redirect("/%s/index/" % MyappConfig.name)

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容"
        if register_form.is_valid():
            # other = register_form.cleaned_data['other']
            # print(other)
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 == password2:
                sample_name_user = User.objects.filter(name=username)
                print(type(sample_name_user))
                if not sample_name_user:
                    sample_email_user = User.objects.filter(email=email)
                    if not sample_email_user:
                        new_user = User.objects.create()
                        new_user.name = username
                        new_user.password = get_md5(password1)
                        new_user.email = email
                        new_user.sex = sex
                        new_user.save()

                        code = make_confirm_string(new_user)#创建确认码
                        send_email(email, code)
                        message = '请前往注册邮箱，进行邮件确认！'
                        app_name = MyappConfig.name
                        return render(request=request, template_name="confirm.html", context=locals())
                    else:
                        message = '该邮箱地址已被注册，请使用别的邮箱！'
                else:
                    message="用户已存在,请重新输入用户名"
            else:
                message = "用户名密码不一致"
    register_form = forms.RegisterForm()
    return render(request=request, template_name="register.html", context=locals())

def logout(request):
    if not request.session.get('is_login', None):
        #如果本来就未登录
        return redirect("/%s/login/" % MyappConfig.name)
    request.session.flush()#一次性将session中的所有内容全部清空，确保不留后患
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/%s/login/" % MyappConfig.name)

#邮件确认
def confirm(request):
    '''
    说明：
    1、通过request.GET.get('code', None)从请求的url地址中获取确认码;
    2、先去数据库内查询是否有对应的确认码;
    3、如果没有，返回confirm.html页面，并提示;
    4、如果有，获取注册的时间create_time，加上设置的过期天数，这里是7天，然后与现在时间点进行对比；
    5、如果时间已经超期，删除注册的用户，同时注册码也会一并删除，然后返回confirm.html页面，并提示;
    6、如果未超期，修改用户的has_confirmed字段为True，并保存，表示通过确认了。然后删除注册码，但不删除用户本身。最后返回confirm.html页面，并提示。

    :param request:
    :return:
    '''
    #http://127.0.0.1:8001/myapp/confirm?code=7eb6b746c3e202769ea797153da7ba2832f13462208e0b8c61bfcb266888098a
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = ConfirmString.objects.get(code=code)
        create_time = confirm.create_time
        now = datetime.datetime.now()
        # 判断是否有效
        if now < create_time + datetime.timedelta(settings.CONFIRM_DAYS):
            confirm.user.has_confirmed = True
            confirm.user.save()
            confirm.delete()
            message = "感谢确认，请使用账户登录！"
        else:
            confirm.user.delete()
            message = '您的邮件已经过期！请重新注册!'
    except:
        message = '无效的确认请求!'
    app_name = MyappConfig.name
    return render(request, 'confirm.html', locals())

def testQuery(request):
    # try:
    user1 = User.objects.get(name="zhangsan")
    user2 = User.objects.filter(name="zhangsan")
    user3 = User.objects.filter(name="zhangsan1")
    print(type(user1))
    print(type(user2))
    print(user3)
    print([type(p) for p in user2])
    import json
    # print(json.dumps(user1, default=lambda obj:obj.__dict__))
    # except DoesNotExist as e:
    #     pass
    return HttpResponse("helloworld")

myapp/templates/base.html
{#通过{% static '相对路径' %}这个Django为我们提供的静态文件加载方法，可以将页面与静态文件链接起来#}
{% comment %}要点：
通过页面顶端的{% load staticfiles %}加载后，才可以使用static方法；
通过{% block title %}base{% endblock %}，设置了一个动态的页面title块；
通过{% block css %}{% endblock %}，设置了一个动态的css加载块；
通过{% block content %}{% endblock %}，为具体页面的主体内容留下接口；
通过{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}将样式文件指向了我们的实际静态文件，下面的js脚本也是同样的道理。{% endcomment %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    {% load staticfiles %}
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Mysite</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'myapp:index'%}">主页</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>
                    <li><a href="{% url 'myapp:logout'%}">登出</a></li>
                {% else %}
                    <li><a href="{% url 'myapp:login'%}">登录</a></li>
                    <li><a href="{% url 'myapp:register'%}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block content %}{% endblock %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

myapp/templates/confirm.html
{% extends 'base.html' %}
{% block title %}注册确认{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-center">{{ message }}</h1>
    </div>
    <script>
        window.setTimeout("window.location='/{{ app_name }}/login/'", 2000);
    </script>
{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    {% if request.session.is_login %}
        <h1>你好,{{ request.session.user_name }}！欢迎回来！</h1>
    {% else %}
        <h1>你尚未<a href="{% url 'myapp:login' %}">登录</a>，只能访问公开内容！</h1>
    {% endif %}
{% endblock %}

myapp/templates/login.html
{% extends 'base.html' %}<!--表示当前页面继承base.html文件中的所有内容-->
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="{% url 'myapp:login'%}" method="post">

                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}

                {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>
                <div class="form-group">
                    {{ login_form.username.label_tag }}
                    {{ login_form.username }}
                </div>
                <div class="form-group">
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                </div>
                <div class="form-group">
                    {{ login_form.captcha.errors }}
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

myapp/templates/login_no_forms.html
{% extends 'base.html' %}<!--表示当前页面继承base.html文件中的所有内容-->
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="{% url 'myapp:login'%}" method="post">

                {% if error %}
                    <div class="alert alert-warning">{{ error }}</div>
                {% endif %}

                {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>
                <div class="form-group">
                    <label for="id_username">用户名：</label>
                    <input type="text" name='username' class="form-control" id="id_username" placeholder="Username"
                           autofocus required>
                </div>
                <div class="form-group">
                    <label for="id_password">密码：</label>
                    <input type="password" name='password' class="form-control" id="id_password" placeholder="Password"
                           required>
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

myapp/templates/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-register' action="{% url 'myapp:register' %}" method="post">

                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">欢迎注册</h2>
                <div class="form-group">
                    {{ register_form.username.label_tag }}
                    {{ register_form.username }}
                </div>
                <div class="form-group">
                    {{ register_form.password1.label_tag }}
                    {{ register_form.password1 }}
                </div>
                <div class="form-group">
                    {{ register_form.password2.label_tag }}
                    {{ register_form.password2 }}
                </div>
                <div class="form-group">
                    {{ register_form.email.label_tag }}
                    {{ register_form.email }}
                </div>
                <!--
                <div class="form-group">
                    <label for="id_other">其他:</label>
                    <input type="text" name="other" class="form-control" id="id_other"/>
                </div>
                -->
                <div class="form-group">
                    {{ register_form.sex.label_tag }}
                    {{ register_form.sex }}
                </div>
                <div class="form-group">
                    <div>
                        {{ register_form.captcha.errors }}
                        {{ register_form.captcha.label_tag }}
                    </div>
                    {{ register_form.captcha }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}